GEMINI_API_KEY = "AIzaSyCKhoUdsFUWxA0UrjTzMgE7ALbQQakSC1g"
PATH_SCREENSHOT = "E:\\Users\\Echo\\Documents\\Python\\Rekvizitai\\screenshots\\"
PATH_CSV = "E:\\Users\\Echo\\Documents\\Python\\Rekvizitai\\documents\\"
PATH_WEB_DRIVER = "E:\\Users\\Echo\\Documents\\Python\\chromedriver.exe"
PATH_TESSERACT_OCR = "C:\\Program Files\\Tesseract-OCR\\tesseract.exe" 